from pydantic.v1 import BaseModel, Field
from typing import List

class BlogPost(BaseModel):
    name: str = Field(
        ..., 
        max_length=255, 
        title="Blog Name", 
        description="Title or name of the Blog, limited to 255 characters."
    )
    content: str = Field(
        ..., 
        title="Content", 
        description="Main content of the Blog."
    )
    excerpt: str = Field(
        ..., 
        title="Excerpt", 
        description="A brief description or excerpt of the blog."
    )
    meta_description: str = Field(
        ..., 
        max_length=300, 
        title="Meta Description", 
        description="SEO meta description of the blog, limited to 300 characters."
    )

    tags: List[str] = Field(..., title="Blog Tags", description="Tags for SEO and categorization")

    effectiveness: int = Field(
        ..., 
        ge=0, le=100, 
        title="Effectiveness Score", 
        description="Effectiveness score of the content, on a scale from 70 to 93 Generate Randomly."
    )
    
    banner_prompt: str = Field(
        ..., 
        title="Banner Prompt", 
        description="Prompt for generating a Realestic blog banner based on the blogs's content and title and the image generated by prompt should not contains text!."
    )